/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analizadorventas.vista;

import analizadorventas.controlador.Controlador;
import analizadorventas.modelo.Transaccion;
import javax.swing.JFileChooser;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;



/**
 *
 * @author root
 */
public class VistaPrincipal extends javax.swing.JFrame {
    List<Transaccion> lista = new ArrayList<>();
    String[] header = {"Nombre del comprador","Producto","Precio", "Fecha de Transaccion", "Ciudad"};
    boolean actualizaFormulario =true;
    boolean borrando = false;
    int vez = 0;
    int registro;
    int destino;
    
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        jTable1.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            //System.out.println("entra");
            if (!borrando){
                if (!fieldNombre.getText().matches("") && !fieldProducto.getText().matches("")
                        && !fieldPrecio.getText().matches("") && !fieldCiudad.getText().matches("") && !fieldFecha.getText().matches("")){
                    Transaccion t = new Transaccion(fieldNombre.getText(), fieldProducto.getText(),
                            Integer.parseInt(fieldPrecio.getText()), fieldFecha.getText(), fieldCiudad.getText());
                    //if (!lista.get(registro).getNombreCliente().matches(fieldNombre.getText())){
                    if (!lista.get(registro).equals(t) && vez < 1){
                        vez++;
                        if (jTable1.getSelectedRow() != -1){
                            destino = jTable1.getSelectedRow();
                            //System.out.println(destino);
                        }
                        //System.out.println("entra 2, " + registro);
                        int valor = JOptionPane.showConfirmDialog(rootPane, "¿Guardar registros?","Guardar",JOptionPane.YES_NO_OPTION);
                        if(valor == JOptionPane.YES_OPTION){
                            actualizaFormulario = false;
                            //System.out.println("entra 4");
                            lista.get(registro).setTransaccion(new Transaccion(fieldNombre.getText(), fieldProducto.getText(), Integer.parseInt(fieldPrecio.getText()),fieldFecha.getText(), fieldCiudad.getText()));
                            //System.out.println(lista.get(registro).getNombreCliente());
                            jTable1.setModel(Controlador.InsertarRegistros(header, lista));
                            actualizaFormulario = true;
                            jTable1.setRowSelectionInterval(destino, destino);
                        }
                        vez = 0;
                    }
                }
            }
            if (jTable1.getSelectedRow() != -1){
                registro = jTable1.getSelectedRow();
                lblEstado.setText("Registro " + (jTable1.getSelectedRow()+1) + " de " + jTable1.getRowCount());
            }
            if (actualizaFormulario){
                //System.out.println("entra 3");
                fieldNombre.setText(lista.get(jTable1.getSelectedRow()).getNombreCliente());
                fieldProducto.setText(lista.get(jTable1.getSelectedRow()).getProductoComprado());
                fieldPrecio.setText(lista.get(jTable1.getSelectedRow()).getPrecio()+"");
                fieldFecha.setText(lista.get(jTable1.getSelectedRow()).getFecha());
                fieldCiudad.setText(lista.get(jTable1.getSelectedRow()).getCiudad());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        fieldNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        fieldProducto = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        fieldPrecio = new javax.swing.JTextField();
        labelFecha = new javax.swing.JLabel();
        fieldFecha = new javax.swing.JTextField();
        lblCiudad = new javax.swing.JLabel();
        fieldCiudad = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MAbrir = new javax.swing.JMenuItem();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.8);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre de comprador", "Producto", "Precio", "Fecha Transaccion", "Ciudad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jSplitPane1.setTopComponent(jScrollPane1);

        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre de usuario:");

        lblProducto.setText("Producto:");

        fieldProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldProductoActionPerformed(evt);
            }
        });

        lblPrecio.setText("Precio:");

        fieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPrecioActionPerformed(evt);
            }
        });

        labelFecha.setText("Fecha Transaccion:");

        fieldFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFechaActionPerformed(evt);
            }
        });

        lblCiudad.setText("Ciudad:");

        fieldCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCiudadActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        lblEstado.setText("Estado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCiudad)
                            .addComponent(labelFecha)
                            .addComponent(lblPrecio)
                            .addComponent(lblNombre)
                            .addComponent(lblProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldNombre)
                            .addComponent(fieldProducto)
                            .addComponent(fieldPrecio)
                            .addComponent(fieldFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(fieldCiudad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addComponent(btnAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSiguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEstado)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto)
                    .addComponent(fieldProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(fieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFecha)
                    .addComponent(fieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCiudad)
                    .addComponent(fieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar)
                    .addComponent(btnNuevo)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(lblEstado)
                .addContainerGap())
        );

        jSplitPane1.setBottomComponent(jPanel1);

        jMenu1.setText("File");

        MAbrir.setText("Abrir");
        MAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(MAbrir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAbrirActionPerformed
        lblEstado.setText("Abriendo archivo");
        int selection = jFileChooser1.showOpenDialog(jMenu1);
        if (selection == JFileChooser.APPROVE_OPTION){
            actualizaFormulario=false;
            lista = Controlador.crearColeccionRegistros(jFileChooser1.getSelectedFile());
            jTable1.setModel(Controlador.InsertarRegistros(header, lista));
            actualizaFormulario=true;
            lblEstado.setText("Archivo abierto");
        }
    }//GEN-LAST:event_MAbrirActionPerformed

    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        lista.get(jTable1.getSelectedRow()).setNombreCliente(fieldNombre.getText());
        int fila = jTable1.getSelectedRow();
        actualizaFormulario=false;
        jTable1.setModel(Controlador.InsertarRegistros(header, lista));
        actualizaFormulario=true;
        jTable1.setRowSelectionInterval(fila, fila);
        lblEstado.setText("Registro actualizado");
    }//GEN-LAST:event_fieldNombreActionPerformed

    private void fieldProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldProductoActionPerformed
        lista.get(jTable1.getSelectedRow()).setProductoComprado(fieldProducto.getText());
        int fila = jTable1.getSelectedRow();
        actualizaFormulario=false;
        jTable1.setModel(Controlador.InsertarRegistros(header, lista));
        actualizaFormulario=true;
        jTable1.setRowSelectionInterval(fila, fila);
        lblEstado.setText("Registro actualizado");
    }//GEN-LAST:event_fieldProductoActionPerformed

    private void fieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPrecioActionPerformed
        lista.get(jTable1.getSelectedRow()).setPrecio(Integer.parseInt(fieldPrecio.getText()));
        int fila = jTable1.getSelectedRow();
        actualizaFormulario=false;
        jTable1.setModel(Controlador.InsertarRegistros(header, lista));
        actualizaFormulario=true;
        jTable1.setRowSelectionInterval(fila, fila);
        lblEstado.setText("Registro actualizado");
    }//GEN-LAST:event_fieldPrecioActionPerformed

    private void fieldFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFechaActionPerformed
        if (fieldFecha.getText().matches("\\d\\d\\d\\d-\\d\\d-\\d\\d")){
            lista.get(jTable1.getSelectedRow()).setFecha(fieldFecha.getText());
            int fila = jTable1.getSelectedRow();
            actualizaFormulario=false;
            jTable1.setModel(Controlador.InsertarRegistros(header, lista));
            actualizaFormulario=true;
            jTable1.setRowSelectionInterval(fila, fila);
            lblEstado.setText("Registro actualizado");
        }
        else
            lblEstado.setText("Fecha incorrecta: usa el formato YYYY-MM-DD");
    }//GEN-LAST:event_fieldFechaActionPerformed

    private void fieldCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCiudadActionPerformed
        lista.get(jTable1.getSelectedRow()).setCiudad(fieldCiudad.getText());
        int fila = jTable1.getSelectedRow();
        actualizaFormulario=false;
        jTable1.setModel(Controlador.InsertarRegistros(header, lista));
        actualizaFormulario=true;
        jTable1.setRowSelectionInterval(fila, fila);
        lblEstado.setText("Registro actualizado");
    }//GEN-LAST:event_fieldCiudadActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        if (jTable1.getSelectedRow()!=0 && jTable1.getSelectedRow()!=-1)
            jTable1.setRowSelectionInterval(jTable1.getSelectedRow()-1, jTable1.getSelectedRow()-1);
        else if (jTable1.getSelectedRow()==0){
            jTable1.setRowSelectionInterval(jTable1.getRowCount()-1, jTable1.getRowCount()-1);
            jScrollPane1.getVerticalScrollBar().setValue(jScrollPane1.getVerticalScrollBar().getMaximum());
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if (jTable1.getSelectedRow()!=jTable1.getRowCount()-1 && jTable1.getSelectedRow()!=-1)
            jTable1.setRowSelectionInterval(jTable1.getSelectedRow()+1, jTable1.getSelectedRow()+1);
        else if(jTable1.getSelectedRow()==jTable1.getRowCount()-1 && jTable1.getSelectedRow()!=-1){
            jTable1.setRowSelectionInterval(0, 0);
            jScrollPane1.getVerticalScrollBar().setValue(jScrollPane1.getVerticalScrollBar().getMinimum());        
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        lista.add(new Transaccion());
        actualizaFormulario =false;
        jTable1.setModel(Controlador.InsertarRegistros(header, lista));
        jScrollPane1.getVerticalScrollBar().setValue(jScrollPane1.getVerticalScrollBar().getMaximum());
        actualizaFormulario=true;
        jTable1.setRowSelectionInterval(jTable1.getRowCount()-1, jTable1.getRowCount()-1);
        lblEstado.setText("Registro insertado");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        borrando = true;
        lista.remove(jTable1.getSelectedRow());
        actualizaFormulario=false;
        jTable1.setModel(Controlador.InsertarRegistros(header, lista));
        actualizaFormulario=true;
        if (registro == jTable1.getRowCount())
            registro-=1;
        jTable1.setRowSelectionInterval(registro, registro);
        borrando=false;
        lblEstado.setText("Registro borrado");
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MAbrir;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JTextField fieldCiudad;
    private javax.swing.JTextField fieldFecha;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldPrecio;
    private javax.swing.JTextField fieldProducto;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProducto;
    // End of variables declaration//GEN-END:variables
}
